# Generated by Django 2.2.6 on 2019-11-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status_Name', models.CharField(default='Not Started', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Name', models.CharField(default='Provide Test Name', max_length=255, unique=True)),
                ('Test_Description', models.TextField(default='')),
                ('Category_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.Category')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('FirstName', models.CharField(default='First Name', max_length=255)),
                ('LastName', models.CharField(default='Last Name', max_length=255)),
                ('Email', models.EmailField(default='Email', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_Question', models.CharField(default='', max_length=255)),
                ('test_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.Test')),
            ],
            options={
                'verbose_name': 'TestQuestion',
                'verbose_name_plural': 'TestQuestions',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Answer', models.CharField(help_text='Answer is matched literally, any single character difference will result in mismatch', max_length=255)),
                ('Options', models.TextField(help_text='Line Feed/New Line separated Options')),
                ('Weight', models.IntegerField(default=1, null=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcq.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField(default=0)),
                ('Timestamp', models.DateTimeField(auto_now=True, verbose_name='Test Attemt Date & Time')),
                ('Test_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.Test')),
                ('Test_Status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mcq.Status', to_field='Status_Name')),
                ('User_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.User')),
            ],
        ),
    ]
