# Generated by Django 2.2.7 on 2019-11-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
