# Generated by Django 2.2.6 on 2019-11-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='Email', max_length=255, primary_key=True, serialize=False, verbose_name='Email'),
        ),
    ]
