# Generated by Django 2.2.6 on 2019-11-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Test_Description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
