# Generated by Django 2.2.6 on 2019-11-28 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_auto_20191127_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='Score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='Test_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.Test', verbose_name='Test ID'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='Timestamp',
            field=models.DateTimeField(verbose_name='Test Attempt Date & Time'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='User_Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.User', verbose_name='Email'),
        ),
    ]
