# Generated by Django 2.2.7 on 2019-11-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_questions_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
