# Generated by Django 2.2.6 on 2019-11-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_auto_20191128_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Test_Id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mcq.Test', verbose_name='Test ID'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('Email', 'Test_Id')},
        ),
    ]
