# Generated by Django 2.2.6 on 2019-11-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_auto_20191128_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Test_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mcq.Test', verbose_name='Test ID'),
        ),
    ]
