# Generated by Django 2.2.6 on 2019-11-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Name',
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='test_Question',
            field=models.CharField(default='', max_length=255),
        ),
    ]
