# Generated by Django 2.2.6 on 2019-11-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0005_auto_20191128_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='Email', max_length=255, primary_key=True, serialize=False, verbose_name='User'),
        ),
    ]
