# Generated by Django 2.2.6 on 2019-11-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0006_auto_20191128_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='User_Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.User', verbose_name='User'),
        ),
    ]
