# Generated by Django 2.2.6 on 2019-11-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0008_auto_20191128_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Test Attempt Date & Time'),
        ),
    ]
