# Generated by Django 2.2.6 on 2019-11-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0010_auto_20191128_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='Total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
    ]
